meetup/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('polls.urls'))
]

polls/urls.py
from django.contrib import admin
from django.urls import path

from .views import (
  PollListView,
  PollDetailView,
  poll_create,
  choice_create,
  number_options,
  vote,
)

app_name = 'polls'
urlpatterns = [
  path('', PollListView.as_view(), name='polls'),
  path('create/', poll_create, name="poll-create"),
  path('create/numer-of-options/', number_options, name="option-number"),
  path('create/add-choice/', choice_create, name="choice-create"),
  path('poll/<int:pk>/', PollDetailView.as_view(), name='poll-detail'),
  path('poll/<int:pk>/vote/', vote, name='poll-vote'),
  # path('ui/', ui, name="ui")

]

polls/models.py
from django.db import models
from django.utils import timezone
from django.urls import reverse
from django.shortcuts import get_object_or_404

# Create your models here.
class Poll(models.Model):
  question = models.CharField(max_length=250)
  creator = models.CharField(max_length=100)
  # pub_date = models.DateTimeField(auto_now_add=True)
  description = models.CharField(max_length=120)
  #options --> point to options database table
  #option_votes --> point to options database table

  def recent(self):
    return self.pub_date >= timezone.now() - datetime.timedelta(days=1)
  

  def __str__(self):
    return self.question

  def get_absolute_url(self):
	  return reverse("polls:poll-detail", kwargs={"pk": self.id})

  # def sort_vote_choices(self):
  #   sorted_options = {
  #     Poll.objects.all():Poll.objects.all().choice_set.all().order_by('option_votes')
  #     }
  #   return sorted_options
class Choice(models.Model):
  poll = models.ForeignKey(Poll, on_delete=models.CASCADE)
  option = models.CharField(max_length=200)
  option_votes = models.IntegerField(default=0)

  def __str__(self):
    return self.option

polls/forms.py
from django import forms
from .models import Poll, Choice


class PollForm(forms.ModelForm):
  class Meta:
    model = Poll
    fields = ('question', 'creator', 'description')

class ChoiceForm(forms.ModelForm):
  class Meta:
    model = Choice
    fields = ('poll', 'option')
  poll = forms.ModelChoiceField(Poll.objects.all())

class ManyOptionsForm(forms.Form):
  number = forms.IntegerField(min_value=2, max_value=10)

polls/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
from django.contrib import messages

# Create your views here.
from .models import (
  Poll,
  Choice
)

from django.views.generic import (
  ListView,
  DetailView,
  CreateView, 
  UpdateView,
  DeleteView
)

from .forms import (PollForm, ChoiceForm, ManyOptionsForm)
from django.forms import formset_factory
# from django.views.generic.edit import (
#   CreateView, 
#   UpdateView,
#   DeleteView
# )
app_name = 'polls'
n = 0
class PollListView(ListView):
  model = Poll
  template_name = 'polls.html'
  queryset = Poll.objects.all()

  def get_object(self):
    id_ = self.kwargs.get("pk")
    return get_object_or_404(Poll, id=id_)

  def get_context_data(self, **kwargs):
    polls = Poll.objects.all()
    context = super().get_context_data(**kwargs)
    context['poll_list'] = polls
    for poll in polls:
      poll.choice_set.all().order_by('option_votes')
      filtered_options = poll.choice_set.all().order_by('option_votes')
      context['sorted_votes'] = {poll.id: filtered_options}
    return context

def poll_create(request):
  if request.method == 'POST':
    form = PollForm(request.POST)
    # multiple_form = ManyOptionsForm(request.POST)
    if form.is_valid():
      form.save()
      return redirect('polls:option-number')
  else:
    form = PollForm()
  return render(request, 'poll-create.html', {'question_form': form})

def number_options(request):
  multiple_form = ManyOptionsForm()
  if request.method == 'POST':
    multiple_form = ManyOptionsForm(request.POST)
    if multiple_form.is_valid():
      print(multiple_form.cleaned_data)
      # multiple_form.save()
      return redirect('polls:choice-create')
  else:
    multiple_form = ManyOptionsForm()
  return render(request, 'decide-option_number.html', {'form':multiple_form})

def choice_create(request):
  number_of_options = 1
  filled_multiple_options_form = ManyOptionsForm(request.POST)

  if filled_multiple_options_form.is_valid():
    number_of_options = filled_multiple_options_form.cleaned_data['number']

  OptionFormSet = formset_factory(ChoiceForm, extra=number_of_options)
  formset = OptionFormSet()

  queryset = Poll.objects.all()
  queryset = list(queryset)[-1]
  if request.method == 'POST':
    filled_formset = OptionFormSet(request.POST)
    if filled_formset.is_valid():
      for form in filled_formset:
        form.save()
      messages.success(request, 'poll created sucessfully!')
      return redirect('polls:polls')
  else:
    formset = OptionFormSet()
  return render(request, 'choice_create.html', {'formset': formset,'poll': queryset})


class PollDetailView(DetailView):
  model = Poll
  template_name = 'poll-detail.html'
  queryset = Poll.objects.all()

  def get_object(self):
    id_ = self.kwargs.get("pk")
    return get_object_or_404(Poll, id=id_)
  
  def get_context_data(self, **kwargs):
    context = super().get_context_data()

    if len(self.get_object().choice_set.filter(option_votes=0))==len(self.get_object().choice_set.all()):
      not_voted = True
      context['not_voted'] = not_voted
    else:
      not_voted = False
      context['not_voted'] = not_voted
    
    return context
  # def get_context_data(self, **kwargs):
  #   context = super().get_context_data(**kwargs)

  #   zero_votes = list(Choice.objects.filter(option_votes=0)

  #   if len(zero_votes) == len(self.get_object.choice_set.all()):
  #     not_voted = True
  #     context['unvoted_list'] = zero_votes
  #   else:
  #     not_voted = False
  #     context['voted_list'] = voted
  #   return context
    
def vote(request, pk):
  question = get_object_or_404(Poll, pk=pk)
  try:
    selected_choice = question.choice_set.get(pk=request.POST['choice'])
  except (KeyError, Choice.DoesNotExist):
    # Redisplay the question voting form.
    return render(request, 'poll-vote.html', {
      'question': question,
      'error_message': "You didn't select a choice.",
    })
  else:
    selected_choice.option_votes += 1
    selected_choice.save()
    # Always return an HttpResponseRedirect after successfully dealing
    # with POST data. This prevents data from being posted twice if a
    # user hits the Back button.
    return redirect('polls:poll-detail', question.id)

def ui(request):
  return render(request,'ui-test.html')

polls/templates/choice_create.html
{% extends 'base.html' %}

{% block title %}
add options
{% endblock %}

{% block content %}
  <svg xmlns="http://www.w3.org/2000/svg" style="display: none;">
    <symbol id="info-fill" fill="currentColor" viewBox="0 0 16 16">
      <path d="M8 16A8 8 0 1 0 8 0a8 8 0 0 0 0 16zm.93-9.412-1 4.705c-.07.34.029.533.304.533.194 0 .487-.07.686-.246l-.088.416c-.287.346-.92.598-1.465.598-.703 0-1.002-.422-.808-1.319l.738-3.468c.064-.293.006-.399-.287-.47l-.451-.081.082-.381 2.29-.287zM8 5.5a1 1 0 1 1 0-2 1 1 0 0 1 0 2z"/>
    </symbol>
    <symbol id="exclamation-triangle-fill" fill="currentColor" viewBox="0 0 16 16">
      <path d="M8.982 1.566a1.13 1.13 0 0 0-1.96 0L.165 13.233c-.457.778.091 1.767.98 1.767h13.713c.889 0 1.438-.99.98-1.767L8.982 1.566zM8 5c.535 0 .954.462.9.995l-.35 3.507a.552.552 0 0 1-1.1 0L7.1 5.995A.905.905 0 0 1 8 5zm.002 6a1 1 0 1 1 0 2 1 1 0 0 1 0-2z"/>
    </symbol>
  </svg>
  <div class="container flex">
  <div class="my-3">
      <div class="alert alert-warning d-flex align-items-center alert-dismissible fade show" role="alert">
        <svg class="bi flex-shrink-0 me-2" width="24" height="24" role="img" aria-label="Warning:"><use xlink:href="#exclamation-triangle-fill"/></svg>
        <div>
          Select the Poll and add an option.
          By chosing the wrong poll, you'll end up writing an option for the wrong Poll!
          </div>
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
          </div>
        </div>
  </div>
  </div>
<div class="container flex">
  <div class="my-3 p-3 bg-body rounded shadow-sm">
    <h4 class="border-bottom pb-2 mb-0">
      {{poll}}
    </h4>
    <div class="d-flex pt-3">
      <svg class="bd-placeholder-img flex-shrink-0 me-2 rounded" width="36" height="36" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Placeholder: 32x32" preserveAspectRatio="xMidYMid slice" focusable="false"><title>Placeholder</title><rect width="100%" height="100%" fill="#007bff"/><text x="50%" y="50%" fill="#007bff" dy=".3em">32x32</text></svg>
      <p class="pb-3 mb-0 small lh-sm">
        <strong class="d-block text-gray-dark text-muted">@{{poll.creator}}</strong>
        <strong class="d-block text-gray-dark text-muted">poll id: {{poll.id}}</strong>
      </p>
    </div>

    <div class="d-flex text-muted pt-3">
      <div class="alert" role="alert">
        <h4 class="alert-heading"></h4>
        <p>Description: {{poll.description}}</p>
        <hr>
        <p class="mb-0"></p>
        {% load widget_tweaks %}
        <form action="." method="post">
        {{formset.management_form}}
        {% for form in formset %}
          {% for field in form %}
          {% csrf_token %}
          <div class="form-group mb-3">
          <label for="exampleFormControlInput1" class="form-label">{{ field.label }}</label>
            {% if field.label == 'Poll' %}
              {% render_field field class="form-select" placeholder="select a poll" %}
            {% else %}
              {% render_field field class="form-control" placeholder="write an option" %}
            {% endif %}
          </div>
          {% endfor %}
          {% endfor %}
          <div class="d-grid gap-2 d-md-flex justify-content-md-end">
            <input class="btn btn-primary" type="submit" value="post poll">
          </div>
        </form>
      </div>
    <div>
</div>
{% endblock %}

polls/templates/decide-option_number.html
{% extends 'base.html' %}
{% block content %}
  <svg xmlns="http://www.w3.org/2000/svg" style="display: none;">
    <symbol id="info-fill" fill="currentColor" viewBox="0 0 16 16">
      <path d="M8 16A8 8 0 1 0 8 0a8 8 0 0 0 0 16zm.93-9.412-1 4.705c-.07.34.029.533.304.533.194 0 .487-.07.686-.246l-.088.416c-.287.346-.92.598-1.465.598-.703 0-1.002-.422-.808-1.319l.738-3.468c.064-.293.006-.399-.287-.47l-.451-.081.082-.381 2.29-.287zM8 5.5a1 1 0 1 1 0-2 1 1 0 0 1 0 2z"/>
    </symbol>
    <symbol id="exclamation-triangle-fill" fill="currentColor" viewBox="0 0 16 16">
      <path d="M8.982 1.566a1.13 1.13 0 0 0-1.96 0L.165 13.233c-.457.778.091 1.767.98 1.767h13.713c.889 0 1.438-.99.98-1.767L8.982 1.566zM8 5c.535 0 .954.462.9.995l-.35 3.507a.552.552 0 0 1-1.1 0L7.1 5.995A.905.905 0 0 1 8 5zm.002 6a1 1 0 1 1 0 2 1 1 0 0 1 0-2z"/>
    </symbol>
  </svg>
  <div class="container flex">
  <div class="my-3">
      <div class="alert alert-warning d-flex align-items-center alert-dismissible fade show" role="alert">
        <svg class="bi flex-shrink-0 me-2" width="24" height="24" role="img" aria-label="Warning:"><use xlink:href="#exclamation-triangle-fill"/></svg>
        <div>
          Write down the number of options for each poll
          </div>
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
          </div>
        </div>
  </div>
  </div>
<div class="container flex">
  <div class="my-3 p-3 bg-body rounded shadow-sm">
    <h5 class="border-bottom pb-2 mb-0">
      Number of Options
    </h5>
    <div class="flex pt-3">
      <form action="{% url 'polls:choice-create' %}" method="post">
        {% load widget_tweaks %}
            {%csrf_token %}
              {% for field in form %}
                <div class=" form-group mb-3">
                  <label for="exampleFormControlInput1" class="form-label">{{ field.label }}</label>
                    {% render_field field class="form-control" placeholder="number of options ex. 2, 3, 4 … etc." %}
                    {{ field.errors }}
              {% endfor %}
            </div>
          <div class="d-grid gap-2 d-md-flex justify-content-md-end">
            <input class="btn btn-primary" type="submit" value=" add choices">
          </div>
      </form>
  </div>
</div>
{% endblock %}

polls/templates/poll-create.html
{% extends 'base.html' %}

{% block title %}
add poll
{% endblock %}

{% block content %}
<div class="container flex">
  <div class="my-3 p-3 bg-body rounded shadow-sm">
    <h5 class="border-bottom pb-2 mb-0">
      Make Poll
    </h5>
    <div class="flex pt-3">
      <form action="." method="post">
        {% load widget_tweaks %}
            {%csrf_token %}
              {% for field in question_form %}
                <div class=" form-group mb-3">
                  <label for="exampleFormControlInput1" class="form-label">{{ field.label }}</label>
                  {% if field.label == 'Question' %}
                    {% render_field field class="form-control" placeholder="ask a question ex. Roadtrip - where to?" %}
                    {{ field.errors }}
                  {% elif field.label == 'Creator' %}
                    {% render_field field class="form-control" placeholder="your name" %}
                  {% else %}
                    {% render_field field class="form-control" placeholder="enter a description" %}
                  {% endif %}
                </div>
              {% endfor %}
            </div>
          <div class="d-grid gap-2 d-md-flex justify-content-md-end">
            <input class="btn btn-primary" type="submit" value=" add choices">
          </div>
      </form>
  </div>
</div>
{% endblock %}

polls/templates/poll-detail.html
{% extends 'base.html' %}
{% block content %}

<div class="container">
  <div class="my-3 p-3 bg-body rounded shadow-sm">
    <h6 class="border-bottom pb-2 mb-0">{{object.question}}</h6>
    <div class="d-flex text-muted pt-3">

      <p class="pb-3 mb-0 small lh-sm border-bottom">
        <strong class="d-block text-gray-dark">@{{object.creator}}</strong>
      </p>
    </div>
    {% if not not_voted %}
      {% for choice in object.choice_set.all %}
        <div class="form-check">
          {{ choice }}: {{  choice.option_votes}}
        </div>
      {% endfor %}

      <a href="{% url 'polls:poll-vote' object.id %}">
        <button type="button" class="btn btn-primary nav-item" data-toggle="button" aria-pressed="false" autocomplete="off">
          Vote
        </button>
      </a>
      {% else %}
        <a href="{% url 'polls:poll-vote' object.id %}">
        <button type="button" class="btn btn-primary nav-item" data-toggle="button" aria-pressed="false" autocomplete="off">
          Vote
        </button>
      </a>
      {% endif %}
    <small class="d-block text-end mt-3">
      <a href="{% url 'polls:polls' %}">back</a>
    </small>
  </div>
</div>
{% endblock %}

polls/templates/poll-vote.html
{% extends 'base.html' %}
{% block content %}

<div class="container">
  <div class="my-3 p-3 bg-body rounded shadow-sm">
    <h6 class="border-bottom pb-2 mb-0">{{question.question}}</h6>
    <div class="d-flex text-muted pt-3">

      <p class="pb-3 mb-0 small lh-sm border-bottom">
        <strong class="d-block text-gray-dark">@{{question.creator}}</strong>
      </p>
    </div>
      <form action="{% url 'polls:poll-vote' question.id %}" method="post">
      {% csrf_token %}
    {% for choice in question.choice_set.all %}
      <div class="form-check">
        <input class="form-check-input" type="radio" name="choice" id="choice" value="{{choice.id}}" checked>
        <label class="form-check-label" for="exampleRadios1">
          {{ choice.option }}
        </label>
      </div>
    {% endfor %}
    <input type="submit" value="Vote" class="btn btn-primary nav-item" data-toggle="button" aria-pressed="false" autocomplete="off">
    </form>
    </div>
  </div>
</div>
{% endblock %}

polls/templates/polls.html
{% extends 'base.html' %}
{% block title %}
Explore Polls
{% endblock %}

{% block content %}
<div class="container flex">
  <div class="my-3 p-3 bg-body rounded shadow-sm">
    <h5 class="border-bottom pb-2 mb-0">
      New Polls 
      <div class="d-grid gap-2 d-md-flex justify-content-md-end">
        <a href="{% url 'polls:poll-create' %}"><button type="button" class="btn btn-outline-primary">Create</button></a>
      </div>
    </h5>
    
    {% for poll in poll_list %}

      <div class="d-flex text-muted pt-3">
        <svg class="bd-placeholder-img flex-shrink-0 me-2 rounded" width="36" height="36" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Placeholder: 32x32" preserveAspectRatio="xMidYMid slice" focusable="false"><title>Placeholder</title><rect width="100%" height="100%" fill="#007bff"/><text x="50%" y="50%" fill="#007bff" dy=".3em">32x32</text></svg>
        <p class="pb-3 mb-0 small lh-sm">
          <strong class="d-block text-gray-dark">@{{poll.creator}}</strong>
          {{poll.question}}
        </p>
      </div>

    <div class="container border-bottom flex">
      <div class="row justify-content-end">
        <div class="col col-lg-2">
          <p>
            <a href="{% url 'polls:poll-vote' poll.id %}">
              <button class="btn btn-primary" role="button" aria-expanded="false">
                Vote
              </button>
            </a>
              <button class="btn btn results" data-bs-toggle="collapse" href="#poll{{poll.id}}" role="button" aria-expanded="false" aria-controls="collapseExample">
                Results
                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-caret-down-fill icon-show" viewBox="0 0 16 16">
                  <path d="M7.247 11.14 2.451 5.658C1.885 5.013 2.345 4 3.204 4h9.592a1 1 0 0 1 .753 1.659l-4.796 5.48a1 1 0 0 1-1.506 0z"/>
                </svg>
              </button>
          </p>         
      </div>
      <!--div class="col">
      <a href="{% url 'polls:choice-create' %}">
        <button type="button" class="btn">
          <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-plus-lg" viewBox="0 0 16 16">
            <path d="M8 0a1 1 0 0 1 1 1v6h6a1 1 0 1 1 0 2H9v6a1 1 0 1 1-2 0V9H1a1 1 0 0 1 0-2h6V1a1 1 0 0 1 1-1z"/>
          </svg>
        </button>
      </a>
      </div-->
      <div class="container flex">
         
          {% for choice in poll.choice_set.all %}
          <div class="my-3 p-3 bg-body rounded shadow-sm collapse" id="poll{{poll.id}}">
            <h4 class="pb-3 mb-0 small lh-sm">{{choice}}: <span class="text-muted ">{{choice.option_votes}} votes</span></h4>
          </div>
          {% endfor %}
          <div class="my-3 bg-body collapse" id="poll{{poll.id}}">
          <a href="{% url 'polls:choice-create' %}">
            <button class="btn btn-outline-primary">
            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-plus-lg" viewBox="0 0 16 16"><path d="M8 0a1 1 0 0 1 1 1v6h6a1 1 0 1 1 0 2H9v6a1 1 0 1 1-2 0V9H1a1 1 0 0 1 0-2h6V1a1 1 0 0 1 1-1z"></svg>
            add another option
            </button>
          </a>
          </div>
    </div>
    </div>
    
    </div>
    {% endfor %}
    <small class="d-block text-end mt-3">
      <a href="#">All updates</a>
    </small>
  </div>
{% endblock %}

polls/templates/ui-test.html
{% extends 'base.html' %}
{% block content %}

<p>
  <a class="btn btn-primary" data-bs-toggle="collapse" href="#collapseExample" role="button" aria-expanded="false" aria-controls="collapseExample">
    Link with href
  </a>
  <button class="btn btn-primary" type="button" data-bs-toggle="collapse" data-bs-target="#collapseExample" aria-expanded="false" aria-controls="collapseExample">
    Button with data-bs-target
  </button>
</p>
<div class="collapse" id="collapseExample">
  <div class="card card-body">
    Some placeholder content for the collapse component. This panel is hidden by default but revealed when the user activates the relevant trigger.
  </div>
</div>

{% endblock %}